# These features will enable a 'Sponsor' button on your repository.

github: [qawwali6969]
# patreon: your_patreon_username
# open_collective: your_collective
# ko_fi: your_kofi_username
# buy_me_a_coffee: your_buymeacoffee_username
# custom: ['https://boosty.to/your_username']
