import SwiftUI
import AppKit

struct ClipboardItem: Identifiable, Equatable {
    let id: UUID
    let content: String
    let timestamp: Date
    var isPinned: Bool
    
    var preview: String {
        let trimmed = content.trimmingCharacters(in: .whitespacesAndNewlines)
        let lines = trimmed.components(separatedBy: .newlines)
        return lines.prefix(2).joined(separator: " ")
    }
    
    var isCodeSnippet: Bool {
        content.contains("function ") ||
        content.contains("def ") ||
        content.contains("const ") ||
        content.contains("import ") ||
        content.contains("{") && content.contains("}") ||
        content.contains("class ") ||
        content.contains("SELECT ") ||
        content.contains("curl ")
    }
    
    static func == (lhs: ClipboardItem, rhs: ClipboardItem) -> Bool {
        lhs.id == rhs.id && lhs.isPinned == rhs.isPinned
    }
}

@MainActor
class ClipboardManager: ObservableObject {
    static let shared = ClipboardManager()
    
    @Published var history: [ClipboardItem] = []
    @Published var searchQuery: String = ""
    
    private var lastChangeCount: Int = 0
    private var timer: Timer?
    
    init() {
        self.lastChangeCount = NSPasteboard.general.changeCount
        // Purge any sensitive secrets if they ever made it into memory
        history.removeAll { ClipboardManager.isSensitiveSecret($0.content) }
        startMonitoring()
    }
    
    func startMonitoring() {
        timer?.invalidate()
        timer = Timer.scheduledTimer(withTimeInterval: 0.5, repeats: true) { [weak self] _ in
            Task { @MainActor [weak self] in
                self?.checkPasteboard()
            }
        }
    }
    
    // MARK: - Secret & Sensitive Content Detection
    static func isSensitiveSecret(_ string: String) -> Bool {
        let trimmed = string.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return false }
        
        // 1. API key & token prefixes
        let secretPrefixes = [
            "sk-", "sk_live_", "sk_test_", "sk-ant-", "sk-proj-", // OpenAI, Anthropic, Stripe
            "AIzaSy", "AQ.Ab", // Google AI Studio / Gemini API
            "ghp_", "gho_", "ghu_", "ghs_", "ghr_", "github_pat_", // GitHub Personal Access Tokens
            "xoxb-", "xoxp-", "xoxa-", "xoxr-", // Slack tokens
            "AKIA", "ASIA", // AWS Access Key IDs
            "SG.", // SendGrid
            "hf_", // HuggingFace
            "npm_", // NPM access tokens
            "glpat-", // GitLab
        ]
        
        for prefix in secretPrefixes {
            if trimmed.hasPrefix(prefix) {
                return true
            }
        }
        
        // 2. Private Keys and Certificates
        if trimmed.contains("-----BEGIN PRIVATE KEY-----") ||
           trimmed.contains("-----BEGIN RSA PRIVATE KEY-----") ||
           trimmed.contains("-----BEGIN OPENSSH PRIVATE KEY-----") ||
           trimmed.contains("-----BEGIN EC PRIVATE KEY-----") ||
           trimmed.contains("-----BEGIN CERTIFICATE-----") {
            return true
        }
        
        // 3. JWT Tokens (header.payload.signature)
        if trimmed.hasPrefix("eyJ") && trimmed.components(separatedBy: ".").count == 3 {
            return true
        }
        
        // 4. Z.ai / BigModel format: 32 hex chars + "." + token (e.g. <32-hex-chars>.<token>)
        if let dotIndex = trimmed.firstIndex(of: ".") {
            let prefix = String(trimmed[..<dotIndex])
            if prefix.count == 32 && prefix.allSatisfy({ $0.isHexDigit }) {
                return true
            }
        }
        
        // 5. Bearer authorization headers
        let lower = trimmed.lowercased()
        if (lower.hasPrefix("bearer ") || lower.hasPrefix("authorization: bearer ")) && trimmed.count > 20 {
            return true
        }
        
        // 6. Generic secret assignments in config/env
        if (lower.contains("api_key=") || lower.contains("apikey=") || lower.contains("secret_key=") || lower.contains("private_key=")) && trimmed.count > 25 {
            return true
        }
        
        return false
    }
    
    /// Checks macOS system-level concealed flags (used by 1Password, Bitwarden, Apple Passwords)
    private func isConcealedPasteboard() -> Bool {
        let pasteboard = NSPasteboard.general
        let concealedTypes = [
            NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
            NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
            NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
            NSPasteboard.PasteboardType("com.agilebits.onepassword"),
            NSPasteboard.PasteboardType("com.typeit4me.clipping")
        ]
        for type in concealedTypes {
            if pasteboard.types?.contains(type) == true {
                return true
            }
        }
        return false
    }
    
    private func checkPasteboard() {
        let currentChangeCount = NSPasteboard.general.changeCount
        guard currentChangeCount != lastChangeCount else { return }
        lastChangeCount = currentChangeCount
        
        // If password manager or OS marked this pasteboard item as concealed, ignore immediately
        if isConcealedPasteboard() {
            return
        }
        
        guard let string = NSPasteboard.general.string(forType: .string) else { return }
        let trimmed = string.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return }
        
        // SECURITY FILTER: Never store sensitive API keys, tokens, or private keys into history
        if ClipboardManager.isSensitiveSecret(string) {
            return
        }
        
        // Check if top item is identical
        if let first = history.first, first.content == string {
            return
        }
        
        // Remove earlier duplicate unpinned item if exists
        history.removeAll { !$0.isPinned && $0.content == string }
        
        let newItem = ClipboardItem(
            id: UUID(),
            content: string,
            timestamp: Date(),
            isPinned: false
        )
        history.insert(newItem, at: 0)
        
        // Keep max 50 items
        if history.count > 50 {
            if let lastUnpinnedIndex = history.lastIndex(where: { !$0.isPinned }) {
                history.remove(at: lastUnpinnedIndex)
            }
        }
    }
    
    func addManualEntry(text: String) {
        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return }
        history.removeAll { !$0.isPinned && $0.content == trimmed }
        let newItem = ClipboardItem(
            id: UUID(),
            content: trimmed,
            timestamp: Date(),
            isPinned: false
        )
        history.insert(newItem, at: 0)
        if history.count > 50 {
            if let lastUnpinned = history.lastIndex(where: { !$0.isPinned }) {
                history.remove(at: lastUnpinned)
            }
        }
    }
    
    func copyToPasteboard(item: ClipboardItem) {
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        pasteboard.setString(item.content, forType: .string)
        self.lastChangeCount = pasteboard.changeCount
    }
    
    func togglePin(item: ClipboardItem) {
        if let idx = history.firstIndex(where: { $0.id == item.id }) {
            history[idx].isPinned.toggle()
        }
    }
    
    func remove(item: ClipboardItem) {
        history.removeAll { $0.id == item.id }
    }
    
    func clearAll() {
        history.removeAll()
    }
    
    func clearUnpinned() {
        history.removeAll { !$0.isPinned }
    }
    
    var filteredItems: [ClipboardItem] {
        if searchQuery.isEmpty {
            return history
        }
        return history.filter { $0.content.localizedCaseInsensitiveContains(searchQuery) }
    }
}
